### ISSUE TITLE
URLs section review

### ISSUE THREAD

**Issue by domenic** [webspecs/url#1]
- It could be made clearer with the addition of non-normative examples.
- "Scheme data" confuses me, and the note below it does not help.
- Relative schemes make sense, but it might be good to add a note explaining why "foo" is not a relative scheme and what implication that has for URLs in the form "foo:bar".

**Comment by rubys** [comment]
> It could be made clearer with the addition of non-normative examples.

Not clear to me what "it" is.  :-)

> "Scheme data" confuses me, and the note below it does not help.

Ah, this is a concrete example of an "it".  And, yes, an example would help.

Consider the following URL, as defined in the (expired!) [draft-hoehrmann-javascript-scheme-03](https://tools.ietf.org/html/draft-hoehrmann-javascript-scheme-03):

```
javascript:doSomething()
```

`javascript` is the `scheme`.  `doSomething()` isn't a  `username`, `password`, `host`, `port`, `path`, `query`, or `fragment`.   `scheme data` is therefore defined to hold this information.

As you say, an example would help here.

> Relative schemes make sense, but it might be good to add a note explaining why "foo" is not a relative scheme and what implication that has for URLs in the form "foo:bar".

In the definition of [non-relative-url](https://specs.webplatform.org/url/webspecs/develop/#non-relative-url), there is the following note:

> The resolution of <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=27233">bug <code>27233</code></a> may add support for relative URLs for unknown schemes.

If you follow that link (and then into the links provided with the first comment), you will see that the implications have yet to be settled.  Input from the TAG would be helpful here.

**Comment by Pomax** [comment]
Hmm, my two cents here: the example you give makes "schema data" feel like an arbitrary catch-all for "things that are not ...", and seems in conflict with the core statement that "A URL is a universal identifier".

Treating `javascript:doSomething()` as an identifier feels like stretching the meaning of the word "identifer" quite a bit, with an attempt made to call everything currently using the [word][colon][thing] format a "URL", whereas I had expected the "javascript:codeGoesHere" string to be an example of what under this new unified and modernized spec we should consider an obsolete format string, and an example of what _isn't_ a URL anymore, despite still being in supported and in use (while at least considered bad practice).

I have no data to back this up, but I seem to recall the `javascript:....` string being a hack to get JS triggered before HTML had an adequate `element event -> javascript handling` system, so this would be an excellent thing to finally retire as "no, we abused the URL notion here and we got stuck with it until now" case.

**Comment by rubys** [comment]
`javascript` is indeed a hack, but in general, once a substantial amount of content is deployed on the Internet, generally "retirement" isn't an option.  In any case, `javascript` is but one example.  There are [plenty more](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).

**Comment by domenic** [comment]
> Not clear to me what "it" is. :-)

Sorry, I meant the URLs section in general.

**Comment by rubys** [comment]
> Sorry, I meant the URLs section in general.

Ah, hence the title of this issue.  DOH!
