### ISSUE TITLE
Remove file-like-scheme?

### ISSUE THREAD

**Issue by domenic** [webspecs/url#7]
It seems you'd gain a decent amount of simplicity by just inlining the string "file" in the appropriate places. As-is, it feels like premature generalization.

**Comment by masinter** [comment]
is "ftp:" a file-like scheme?

**Comment by domenic** [comment]
Nope:
- https://specs.webplatform.org/url/webspecs/develop/#file-like-scheme
- https://specs.webplatform.org/url/webspecs/develop/#non-file-relative-scheme

**Comment by rubys** [comment]
@dominic: be aware that one of those two links is likely to be short-lived. :-)

(put another way, I agree with this request, and plan to address it shortly)

**Comment by masinter** [comment]
I meant "shouldn't ftp be a file-like scheme"? Such that the "generalization" isn't "premature", if there's possibly other cases?

At least, 

ftp:\ftp.rfc-editor.org\in-notes\rfc1738.txt
turns into
ftp://ftp.rfc-editor.org/in-notes/rfc1738.txt

when typed into address bar in Chrome and IE11 

i could make some test cases, I suppose, if it was clear where to put them.

**Comment by domenic** [comment]
If that's the criteria, then http is also a file-like scheme. typing

http:\ftp.rfc-editor.org\in-notes\rfc1738.txt

turns into

http://ftp.rfc-editor.org/in-notes/rfc1738.txt

before being redirected to

https://www.rfc-editor.org/in-notes/rfc1738.txt

**Comment by rubys** [comment]
@masinter:

> i could make some test cases, I suppose, if it was clear where to put them.

The place to put them is [urltestdata.txt](https://github.com/w3c/web-platform-tests/blob/master/url/urltestdata.txt).  [web-platform-tests](https://github.com/w3c/web-platform-tests) accepts [pull requests](https://github.com/w3c/web-platform-tests/pulls pull requests).

The format is a bit... arcane.  The [URL Test Results](https://url.spec.whatwg.org/interop/urltest-results/) page may help not only in deciphering the format, but also to see comparative results with a variety of user agents.
